version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vlab-db
    restart: always
    environment:
      POSTGRES_USER: vlab_user
      POSTGRES_PASSWORD: vlab_pass
      POSTGRES_DB: vlab_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
